### ISSUE TITLE
gatb-pipeline requires a Linux 64 bits system

### ISSUE THREAD

**Issue by anmwinter** [GATB/gatb-minia-pipeline#14]
Morning,

  I am on a Intel Core i& (64bit) Mac running OSX 10.11.6 with Xcode and Anaconda installed. When I run the make test or gatb directly I get the following error:
`gatb-pipeline requires a Linux 64 bits system`

I do have bcalm and bloocoo install individually and they are running fine. I was wondering if there is a work around for this?

Thanks!
ara

**Comment by rchikhi** [comment]
hi ara,
you'd need bloocoo and minia compiled on your system, and put the binaries there instead of the linux64 ones.
then, just delete those lines in the gatb script:
```
from sys import platform
if platform == "darwin":
    exit("gatb-pipeline requires a Linux 64 bits system")
```

There might be other problems down the road, but I'd be happy to assist.

Best,
Rayan

**Comment by bioinfonm** [comment]
Rayan,

  Thanks! I'll give that a try.

ara
