### ISSUE TITLE
Execution of 'perl tools/sga-deinterleave.pl'

### ISSUE THREAD

**Issue by Shirley-Q** [GATB/gatb-minia-pipeline#16]
Hi,
There was an error as fllowed. I can not find the reason. could you help me?
(2019-05-25 03:32:29) Execution of 'perl tools/sga-deinterleave.pl'. Command line: 
     perl /home/emma/gatb-minia-pipeline/tools/sga-deinterleave.pl trim.fq assembly.lib0_1.fq assembly.lib0_2.fq
Found two consecutive /1 read headers, exiting; (last header: @RM2|S1|R22652116/1) at /home/emma/gatb-minia-pipeline/tools/sga-deinterleave.pl line 52, <IN> line 8.
(2019-05-25 03:32:30) Execution of 'perl tools/sga-deinterleave.pl' failed. Command line: 
     perl /home/emma/gatb-minia-pipeline/tools/sga-deinterleave.pl trim.fq assembly.lib0_1.fq assembly.lib0_2.fq

Best wishes,
Shirley

**Comment by Shirley-Q** [comment]
(2019-05-25 03:47:59) Execution of 'python BESST/runBESST'. Command line: 
     /home/emma/gatb-minia-pipeline/tools/memused python /home/emma/gatb-minia-pipeline/BESST/runBESST -c assembly_k31.contigs.fa -f assembly.lib_0.bam -o assembly_besst -orientation fr --iter 10000
Number of initial contigs: 32
There was another error.
Estimating insert size from 48 mappings with quality over --min_mapq 11.
To few valid read alignments exists to compute mean and variance of library (need at least 1000 observations). Got only 47 valid alignments. Please specify -m and -s to the program. 
Printing out scaffolds produced in earlier steps...
terminating...
maximal memory used: 85 MB
Error: BESST returned no results in assembly_besst/

**Comment by rchikhi** [comment]
Hi Shirley, sorry for the late response. Did you end up figuring the issue?

**Comment by Shirley-Q** [comment]
yes， I re-install the atb-minia-pipeline. And No longer have this problem. But I have new error as described in nohup.out file. Thank you very much!


best wishes,
Shirley




------------------ 原始邮件 ------------------
发件人: "Rayan Chikhi"<notifications@github.com>;
发送时间: 2019年6月2日(星期天) 晚上8:50
收件人: "GATB/gatb-minia-pipeline"<gatb-minia-pipeline@noreply.github.com>;
抄送: "乔雪姣"<1678141559@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [GATB/gatb-minia-pipeline] Execution of 'perltools/sga-deinterleave.pl' (#16)




Hi Shirley, sorry for the late response. Did you end up figuring the issue?

**Comment by rchikhi** [comment]
What's the contents of this nohup.out file?
