### ISSUE TITLE
Combining multiple libraries

### ISSUE THREAD

**Issue by harish0201** [GATB/gatb-minia-pipeline#20]
Hi!

I have a couple of older Illumina datasets (both PE and MP) split across multiple insert sizes and libraries.

Is it possible to pass them as a single argument, as I think that'd make life easy.

Would a FIFO sort of approach work? Or should I give a file of files (FOF) ? I believe that the FOF approach works only for SE-Reads rather than PE.

If needed I can pass MP libraries later to scaffold only.

What would you suggest?

**Comment by rchikhi** [comment]
Hi! Apologies for the delayed answer. Indeed the FOF strategy doesn't work.
You'll need to
1) if applicable, for each insert size, concatenate all the left (resp. right) files from that insert size into a single left (resp. right) file
2) pass using `-1 left_insertA.fq.gz -2 right_insertA.gz --mp-1 left_insertB.fq.gz --mp-2 right_insertB.fq.gz` in order from smaller insert size to larger (ie in my example, insert size A is smaller than B)

**Comment by harish0201** [comment]
Thank you for the suggestion and apologies for the delayed response! 

I did use a mixture of the two options though. I concatenated the smaller insert fastqs and used the mate-pair separately.

**Comment by rchikhi** [comment]
sounds good, did it work?

**Comment by harish0201** [comment]
Yup, it did! I got a decent contiguity as well.

Got the 2.5Gb genome in 9876 (no joke) scaffolds over 1kb in length with an N50 of 1.83Mb. Having a 8Kb and 20Kb insert MP libraries did help a lot combined with dual scaffolding.

**Comment by rchikhi** [comment]
very nice!
