### ISSUE TITLE
Add version info on prerequisites

### ISSUE THREAD

**Issue by nylander** [GATB/gatb-minia-pipeline#21]
Hi,

consider specifying the preferred versions of needed software.

In particular: `bwa`, `mathstats`, `scipy`, `networkx`, `pysam`.

This would help tremendously when debugging the installation procedure.

Thanks
Johan

**Comment by rchikhi** [comment]
Thanks for reporting this. I've removed all those prerequisites and replaced them by just one: BESST. (as they were prerequisites of BESST, actually).
