### ISSUE TITLE
Error with `make test`

### ISSUE THREAD

**Issue by nylander** [GATB/gatb-minia-pipeline#22]
Hi,

Following the installation instructions, `make test` fails with an Error (from `runBESST`). Is the test correctly designed?

To reproduce:

- Ubuntu 18.04.3 LTS
- python version 2.7.15+
- pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)
- mathstats version 0.2.6.5
- networkx version 2.2
- scipy version 1.2.2
- pyfasta version 0.5.2
- pysam version 0.8.3
- bwa version 0.7.17-r1188
- samtools version 1.7 (using htslib 1.7-2)

```
$ make test
...
Processing is finished.
(2019-12-16 08:32:42) Execution of 'python BESST/runBESST'. Command line: 
     gatb-minia-pipeline/tools/memused python gatb-minia-pipeline/BESST/runBESST -c assembly_k61.contigs.fa -f assembly.lib_0.bam -o assembly_besst -orientation fr --iter 10000
Number of initial contigs: 1
Estimating insert size from 10001 mappings with quality over --min_mapq 11.
Choosing mode: 495
mu_adjusted:499.4076, sigma_adjusted:49.8135148553, skewness_adjusted:-0.0259150237889
Creating contig graph with library:  assembly.lib_0.bam
Too few contigs to calculate coverage on. Got: 1 contigs. If you have specified  -z_min or --min_mapq, consider lower them. If not, check the BAM file for proper alignments. Exiting here before scaffolding...
maximal memory used: 84 MB
(2019-12-16 08:32:44) Execution of 'python BESST/runBESST' failed. Command line: 
     gatb-minia-pipeline/tools/memused python gatb-minia-pipeline/BESST/runBESST -c assembly_k61.contigs.fa -f assembly.lib_0.bam -o assembly_besst -orientation fr --iter 10000
Makefile:14: recipe for target 'test' failed
make: *** [test] Error 1
Processing is finished.
(2019-12-16 08:32:42) Execution of 'python BESST/runBESST'. Command line: 
     gatb-minia-pipeline/tools/memused python gatb-minia-pipeline/BESST/runBESST -c assembly_k61.contigs.fa -f assembly.lib_0.bam -o assembly_besst -orientation fr --iter 10000
Number of initial contigs: 1
Estimating insert size from 10001 mappings with quality over --min_mapq 11.
Choosing mode: 495
mu_adjusted:499.4076, sigma_adjusted:49.8135148553, skewness_adjusted:-0.0259150237889
Creating contig graph with library:  assembly.lib_0.bam
Too few contigs to calculate coverage on. Got: 1 contigs. If you have specified  -z_min or --min_mapq, consider lower them. If not, check the BAM file for proper alignments. Exiting here before scaffolding...
maximal memory used: 84 MB
(2019-12-16 08:32:44) Execution of 'python BESST/runBESST' failed. Command line: 
     gatb-minia-pipeline/tools/memused python gatb-minia-pipeline/BESST/runBESST -c assembly_k61.contigs.fa -f assembly.lib_0.bam -o assembly_besst -orientation fr --iter 10000
Makefile:14: recipe for target 'test' failed
make: *** [test] Error 1
```

### File `assembly_k61.contigs.fa`:
```
Nseqs Min.len Max.len Avg.len
1         9985     9985     9985
```
### File `assembly.lib_0.bam`:
```
$ samtools flagstat assembly.lib_0.bam
20000 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
20000 + 0 mapped (100.00% : N/A)
20000 + 0 paired in sequencing
10000 + 0 read1
10000 + 0 read2
20000 + 0 properly paired (100.00% : N/A)
20000 + 0 with itself and mate mapped
0 + 0 singletons (0.00% : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)
```

**Comment by osowiecki** [comment]
Aligning with bwa mem.
Temp directory: /media/2/CORN/gatb-minia-pipeline/test/BESST_tmp
Output path:    assembly.lib_0
Stderr file:    assembly.lib_0.bwa.1
Make bwa index... Done.
Align with bwa mem... Done.
Time elapsed for bwa index and mem:  0:00:00.572580

Convert SAM to BAM... Done.
Time elapsed for SAM to BAM conversion: 0:00:00.166237

Sort BAM... Done.
Time elapsed for BAM sorting: 0:00:00.136098

Index BAM... Done.
Time elapsed for BAM indexing: 0:00:00.012084

Remove temp files... Done.
Time elapsed for temp files removing: 0:00:00.000678

Processing is finished.
(2019-12-24 18:19:17) Execution of 'python BESST/runBESST'. Command line: 
     /media/2/CORN/gatb-minia-pipeline/tools/memused python /media/2/CORN/gatb-minia-pipeline/BESST/runBESST -c assembly_k61.contigs.fa -f assembly.lib_0.bam -o assembly_besst -orientation fr --iter 10000
Number of initial contigs: 1
Estimating insert size from 10001 mappings with quality over --min_mapq 11.
Choosing mode: 495
mu_adjusted:499.4076, sigma_adjusted:49.8135148553, skewness_adjusted:-0.0259150237889
Creating contig graph with library:  assembly.lib_0.bam
Too few contigs to calculate coverage on. Got: 1 contigs. If you have specified  -z_min or --min_mapq, consider lower them. If not, check the BAM file for proper alignments. Exiting here before scaffolding...
maximal memory used: 61 MB
(2019-12-24 18:19:18) Execution of 'python BESST/runBESST' failed. Command line: 
     /media/2/CORN/gatb-minia-pipeline/tools/memused python /media/2/CORN/gatb-minia-pipeline/BESST/runBESST -c assembly_k61.contigs.fa -f assembly.lib_0.bam -o assembly_besst -orientation fr --iter 10000
Makefile:14: recipe for target 'test' failed
make: *** [test] Error 1

**Comment by sebschmi** [comment]
I am getting the same error for the k61 test case, also just one contig generated.

**Comment by rchikhi** [comment]
thanks for reporting it. Fixed by removing BESST from the test.
