### ISSUE TITLE
920: syntax error in expression (error token is "920")

### ISSUE THREAD

**Issue by osowiecki** [GATB/gatb-minia-pipeline#23]
(2019-12-24 19:56:17) Minia assembling at k=21 min_abundance=2
(2019-12-24 19:56:17) Execution of 'minia/minia'. Command line: 
     /NGStools/gatb-minia-pipeline/tools/memused /NGStools/gatb-minia-pipeline/minia/minia -in assembly.list_reads -kmer-size 21 -abundance-min 2 -out assembly_k21
Minia 3, git commit 40f35ad
setting storage type to hdf5
[Approximating frequencies of minimizers ]  0    %   elapsed:   0 min 0  sec   remaining:   0 min 0  sec   cpu:  -1.0 %   mem: [  22,   22,   22] MB /NGStools/gatb-minia-pipeline/tools/memused: line 13: 22872
920: syntax error in expression (error token is "920")
[Approximating frequencies of minimizers ]  100  %   elapsed:   0 min 29 sec   remaining:   0 min 0  sec   cpu:  93.9 %   mem: [  22,   22,   22] MB 
[DSK: Pass 1/1, Step 1: partitioning     ]  0    %   elapsed:   0 min 0  sec   remaining:   0 min 0  sec   cpu:  -1.0 %   mem: [  76,   76,   91] MB

**Comment by rchikhi** [comment]
Thanks for the report! It's an inconsequential bug in the `memused` script that reports memory usage. I'm having trouble reproducing it on small datasets. Probably won't fix.
