### ISSUE TITLE
BESST: error: unrecognized arguments: fr

### ISSUE THREAD

**Issue by cimendes** [GATB/gatb-minia-pipeline#25]
Hello!

I've been trying to run gatb-minia-pipeline and although it seems to be producing an assembly (a file called `*_final.contigs.fa), i've been getting the following error right at the end of the pipeline. As the error is not something that is controlled by the user, but rather defined in your python script/pipeline, I thought I should share it here. 

I'm running the pipeline with the following command: `gatb -1 ${fastq_pair[0]} -2 ${fastq_pair[1]} --kmer-sizes ${kmer_list} -o ${sample_id}_GATBMiniaPipeline --no-error-correction`

And this is the error that I have:

```
Remove temp files... Done.
Time elapsed for temp files removing: 0:00:00.009432

Processing is finished.
(2020-07-22 08:32:20) Execution of 'python BESST/runBESST'. Command line:
     /NGStools/gatb-minia-pipeline/tools/memused python /NGStools/gatb-minia-pipeline/BESST/runBESST -c ERR2984773_GATBMiniaPipeline_k181.contigs.fa -f ERR2984773_GATBMiniaPipeline.lib_0.bam -o ERR2984773_GATBMiniaPipeline_besst -orientation fr --iter 10000
usage: BESST [-h] -c CONTIGFILE -f BAMFILES [BAMFILES ...]
             [-r READLEN [READLEN ...]] [-m MEAN [MEAN ...]]
             [-s STDDEV [STDDEV ...]] [-z COVCUTOFF [COVCUTOFF ...]]
             [-T THRESHOLD [THRESHOLD ...]] [-e EDGESUPPORT [EDGESUPPORT ...]]
             [-k MINSIZE [MINSIZE ...]] [-filter_contigs CONTIG_FILTER_LENGTH]
             [--min_mapq MIN_MAPQ] [--iter PATH_THRESHOLD]
             [--score_cutoff SCORE_CUTOFF] [--max_extensions MAX_EXTENSIONS]
             [--bfs_traversal] [-a HAPLRATIO] [-b HAPLTHRESHOLD] [-K KMER]
             [-M MMER] [-g] [--orientation ORIENTATION [ORIENTATION ...]]
             [-o OUTPUT] [-d] [-y] [-q] [--no_score] [-devel] [-plots]
             [--separate_repeats] [--NO_ILP] [--FASTER_ILP] [--print_scores]
             [--version]
BESST: error: unrecognized arguments: fr
maximal memory used: 0 MB
(2020-07-22 08:32:21) Execution of 'python BESST/runBESST' failed. Command line:
     /NGStools/gatb-minia-pipeline/tools/memused python /NGStools/gatb-minia-pipeline/BESST/runBESST -c ERR2984773_GATBMiniaPipeline_k181.contigs.fa -f ERR2984773_GATBMiniaPipeline.lib_0.bam -o ERR2984773_GATBMiniaPipeline_besst -orientation fr --iter 10000
```

Any help overcoming this problem is highly appreciated! 

Best,

Inês

**Comment by rchikhi** [comment]
Hi Inês,

Ah, this seems to be a problem with how the gatb script calls BESST
Can you try changing "-orientation" to "--orientation" in the `gatb` file, at this line?
https://github.com/GATB/gatb-minia-pipeline/blob/08e3bcd44b088f976ff7e40e3b53df7e72bcda7b/gatb#L469


Rayan

**Comment by cimendes** [comment]
I've created a PR with the fix. I've run the tool with the fix at it went smoothly :)

**Comment by rchikhi** [comment]
ah great, thanks! good to hear
