### ISSUE TITLE
Question about input file type

### ISSUE THREAD

**Issue by YuanwenGuo** [GATB/gatb-minia-pipeline#29]
Hello minia group,

I wonder if it's possible to run scaffolding if I only have illumina pair end reads, without any mate pair reads? 

It seems BESST needs mate pair reads, because "-orientation" is one of required fields, and commonly only mate pair reads provide this kind of information (If I did't understand wrongly). But for gatb-minia-pipeline, only raw fastq reads is required for inputs. Therefore, I am not sure whether mate pair reads is necessary for scaffolding in gatb-minia-pipeline?

Thank you,
Yuanwen

**Comment by rchikhi** [comment]
Hi, yes it is possible, paired-end orientation is usually rf. Mate-pairs aren't necessary. Note that paired-end scaffolding adds relatively little benefits (just some extra contiguity)

**Comment by YuanwenGuo** [comment]
Thank you! I will give it a try.

Best,
Yuanwen
