### ISSUE TITLE
OSError: [Errno 17] File exists

### ISSUE THREAD

**Issue by mergi-2674** [GATB/gatb-minia-pipeline#32]
I was running gatb-minia-pipeline on my data set and get this error.

Traceback (most recent call last):
  File "/home/apps/user_apps/piwczyn/mergi_apps/gatb-minia-pipeline/gatb", line 606, in <module>
    os.symlink(previous_contigs.rsplit("/", 1)[-1], prefix+"_final.contigs.fa")     # create system link in same location as files
OSError: [Errno 17] File exists
~                               
What is the possible error and how to fix it?
thanks!

**Comment by rchikhi** [comment]
Hi, this error is inconsequential,  Your results are in [prefix]_final.contigs.fa file .
