### ISSUE TITLE
Error with samtools in `make test`

### ISSUE THREAD

**Issue by ppericard** [GATB/gatb-minia-pipeline#8]
When trying to compile and test using `make test`, the compilation stops with an error related to samtools:

$ make test
...
(2016-05-25 13:57:31) Execution of 'python BESST/scripts/reads_to_ctg_map.py'. Command line: 
     python /home/pericard/programmes/gatb-minia-pipeline/BESST/scripts/reads_to_ctg_map.py --tmp_path /home/pericard/programmes/gatb-minia-pipeline/test/BESST_tmp --threads 4 assembly.lib0_1.fa assembly.lib0_2.fa assembly_k61.contigs.fa assembly.lib_0

pe1_path: assembly.lib0_1.fa
pe2_path: assembly.lib0_2.fa
genome_path: assembly_k61.contigs.fa
output_path: assembly.lib_0
tmp_path: /home/pericard/programmes/gatb-minia-pipeline/test/BESST_tmp
bwa path: bwa
number of threads: 4
Remove temp SAM and BAM files: No
Use bwa aln and sampe instead of bwa mem: No

Start processing.

Aligning with bwa mem.
Temp directory: /home/pericard/programmes/gatb-minia-pipeline/test/BESST_tmp
Output path:    assembly.lib_0
Stderr file:    assembly.lib_0.bwa.1
Make bwa index... Done.
Align with bwa mem... Done.
Time elapsed for bwa index and mem:  0:00:00.219248

Convert SAM to BAM... Done.
Time elapsed for SAM to BAM conversion: 0:00:00.109462

Sort BAM...Traceback (most recent call last):
  File "/home/pericard/programmes/gatb-minia-pipeline/BESST/scripts/reads_to_ctg_map.py", line 317, in <module>
    tmp_path, args.bwa_path, args.clear)
  File "/home/pericard/programmes/gatb-minia-pipeline/BESST/scripts/reads_to_ctg_map.py", line 184, in bwa_mem
    pysam.sort(bwa_output + ".bam", output_path)
  File "/usr/local/lib/python2.7/dist-packages/pysam/utils.py", line 65, in __call__
    "\n".join(stderr)))
pysam.utils.SamtoolsError: 'samtools returned with error 1: stdout=, stderr=[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files\n\nUsage: samtools sort [options...] [in.bam]\n\nOptions:\n\n  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)\n\n  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]\n\n  -n         Sort by read name\n\n  -o FILE    Write final output to FILE rather than standard output\n\n  -T PREFIX  Write temporary files to PREFIX.nnnn.bam\n\n  -@, --threads INT\n\n             Set number of sorting and compression threads [1]\n\n      --input-fmt-option OPT[=VAL]\n\n               Specify a single input file format option in the form\n\n               of OPTION or OPTION=VALUE\n\n  -O, --output-fmt FORMAT[,OPT[=VAL]]...\n\n               Specify output format (SAM, BAM, CRAM)\n\n      --output-fmt-option OPT[=VAL]\n\n               Specify a single output file format option in the form\n\n               of OPTION or OPTION=VALUE\n\n      --reference FILE\n\n               Reference sequence FASTA FILE [null]\n'
(2016-05-25 13:57:31) Execution of 'python BESST/scripts/reads_to_ctg_map.py' failed. Command line: 
     python /home/pericard/programmes/gatb-minia-pipeline/BESST/scripts/reads_to_ctg_map.py --tmp_path /home/pericard/programmes/gatb-minia-pipeline/test/BESST_tmp --threads 4 assembly.lib0_1.fa assembly.lib0_2.fa assembly_k61.contigs.fa assembly.lib_0
make: *** [test] Erreur 1

I was thinking about a pb with samtools version so I tested with both samtools v0.1.19 and v1.3.1 without any change.

**Comment by rchikhi** [comment]
This is an error with Pysam 0.9.0 it seems. Until it is resolved, we'll support pysam <=0.8.3 only?
